apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    component: app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
